from setuptools import setup, find_packages

setup(
    name='tesla',
    version='0.0.1',
    packages=find_packages(),
    setup_requires=['wheel'],
    install_requires=[
        'certifi',
        'charset-normalizer',
        'configparser',
        'contourpy',
        'cycler',
        'decorator',
        'entrypoints',
        'fonttools',
        'greenlet',
        'idna',
        'importlib-resources',
        'kiwisolver',
        'lxml',
        'markdown-it-py',
        'matplotlib',
        'mdurl',
        'numpy',
        'obspy',
        'packaging',
        'pandas',
        'pillow',
        'pygments',
        'PyMySQL',
        'pyparsing',
        'python-dateutil',
        'python-math',
        'pytz',
        'PyYAML',
        'requests',
        'rich',
        'scipy',
        'six',
        'SQLAlchemy',
        'typing-extensions',
        'tzdata',
        'urllib3',
        'zipp',
    ],
    entry_points={
        'console_scripts': [
            'Tesla = tesla.main:main',
        ],
    },
    author='Guido Maria Adinolfi',
    author_email='guidomaria.adinolfi@unito.it',
    description='TESLA, a Tool for automatic Earthquake low‐frequency Spectral Level estimation',
    keywords='earthquake, seismology, source spectra, focal mechanism',
    url='https://github.com/DrGMA/TESLA',
    project_urls={
        'Source Code': 'https://github.com/DrGMA/tesla',
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: EUROPEAN UNION PUBLIC LICENCE v. 1.2', 
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    license='EUROPEAN UNION PUBLIC LICENCE v. 1.2',
    long_description="""
A tool for automatic Earthquake low‐frequency Spectral Level estimation.

**Citation:**
Adinolfi, G. M., V. Convertito, and R. De Matteis (2023). TESLA, A Tool for Automatic Earthquake Low-Frequency Spectral Level Estimation: The Study of 2013 St. Gallen Earthquake Fault-Plane Solutions, Seismol. Res. Lett., 94(5), 2441-2455. doi:10.1785/0220230033.
""",
    long_description_content_type='text/markdown',
)
